### ISSUE TITLE
Misc Tasks

### ISSUE THREAD

**Issue by StefanGreve** [StefanGreve/website#7]
Miscellaneous small tasks that require attention.

## TODO

- [ ] Add linter through Git hooks
- [ ] Add branch protection rules for master
- [ ] Add custom favicon
- [ ] edit meta tags
- [ ] rewrite readme file
- [ ] think about other things to add in preparation for deployment
- [ ] embedded [this icon library](https://github.com/ng-icons/ng-icons) and remove all references to `adv-icons`
